version: "3.1"

services:

  onlineshop-database:
    image: onlineshop-db
    ports:
      - "1433:1433"
    networks:
      - app-net

  onlineshop-api:
    image: onlineshop-api
    ports:
      - "8080:8080" 
    depends_on:
      - onlineshop-database
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat