version: "3.1"

services:
  reverse_proxy:
    depends_on:
      - appserver
    image: nginx:1.31.4-alpine-slim
    ports:
      - "80:80"
      - "443:443"
#   user: nginx
    networks:
      - front-tier
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - revprox_cert
      - revprox_key
  database:
    build: 
       context: ./database
    image: onlineshop_db
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: onlineshop
    expose:
      - "5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    depends_on:
      - database
      - payment_gateway
    build:
       context: app
       dockerfile: Dockerfile
    image: onlineshop_app
    user: gordon
    expose:
      - "8080" 
      - "5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  payment_gateway:
    depends_on:
      - database
    build:
      context: payment_gateway
    networks:
      - payment
    secrets:
      - payment_token

networks:
  front-tier:
  back-tier:
  payment:
    #    driver: overlay

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
  revprox_cert:
    file: ./reverse_proxy/domain.crt
  revprox_key:
    file: ./reverse_proxy/domain.key
