FROM node:latest
WORKDIR /usr/src/onlineshop/app/react-app
COPY react-app .
RUN npm install
RUN npm run build

FROM maven:latest
WORKDIR /usr/src/onlineshop
COPY pom.xml .
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
COPY . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests

FROM java:8-jdk-alpine
WORKDIR /static
COPY --from=0 /usr/src/onlineshop/app/react-app/build/ .
WORKDIR /app
COPY --from=1 /usr/src/onlineshop/target/OnlineShop-0.0.1-SNAPSHOT.jar .
EXPOSE 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005","-jar", "/app/OnlineShop-0.0.1-SNAPSHOT.jar"]
CMD ["--spring.profiles.active=postgres"]
